version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
    groups:
      react-runtime:
        patterns:
          - "react"
          - "react-dom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps"
